source 'https://github.com/CocoaPods/Specs.git'

workspace 'Anypic'

pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseCrashReporting'
pod 'ParseUI'
pod 'Facebook-iOS-SDK'

pod 'BuddyBuildSDK', :git => 'https://github.com/iOSTestApps/essdeekay.git', :branch => 'sso'